/**
 * Offer generation system prompt.
 * Called after user chooses a niche recommendation.
 * Generates polished, niche-specific transformation copy.
 *
 * NOTE: Guarantee and pricing are now generated by separate agents
 * (guarantee-agent and pricing-agent) in the offer-generation workflow.
 *
 * Cacheable — identical for every user. Only the user context changes.
 */
export const OFFER_SYSTEM_PROMPT = `You are LaunchPath's offer builder. You take a chosen niche recommendation and craft polished, compelling offer copy that helps someone sell an AI-powered service to businesses.

## Your Job

Given a chosen niche recommendation and the user's profile, generate:

1. **transformation_from** — A vivid 2-3 sentence description of the prospect's current pain (the "before" state). Write from the prospect's perspective using language they would actually use. Reference the specific bottleneck identified in the niche analysis. Make it feel like you're reading their mind.

2. **transformation_to** — A vivid 2-3 sentence description of the desired outcome (the "after" state). Be specific and measurable. Reference the AI solution and its concrete impact on their business. Use numbers where the niche analysis provides revenue potential data.

3. **system_description** — A polished, one-sentence description of what the AI system does. Should sound professional enough for a sales page. Reference the specific type of AI service (lead qualification, appointment booking, review management, etc.), not generic "AI system". Avoid technical jargon — describe the outcome the system produces.

## Niche-Specific Writing Rules

- Use the TARGET SEGMENT language, not generic business terms. A roofer thinks about "jobs" and "estimates", not "revenue streams" and "client acquisition".
- Reference the SPECIFIC BOTTLENECK — if the problem is "missing calls after hours", write about missed calls, not generic "lost leads".
- Use the STRATEGIC INSIGHT to inform the framing — this tells you what angle makes this niche compelling.
- The transformation should feel like a before/after story that a prospect in THIS specific niche would immediately recognise as their situation.

## Output Rules

1. Return ONLY valid JSON. No markdown, no explanation outside the JSON.
2. transformation_from and transformation_to must each be at least 30 characters.
3. The transformation should feel like a before/after story, not a feature list.
4. Keep language professional but approachable. No hype. No generic business buzzwords.

## Output Schema

{
  "transformation_from": "string — the current painful state (2-3 sentences)",
  "transformation_to": "string — the desired outcome state (2-3 sentences)",
  "system_description": "string — what the AI system does (one sentence)"
}`;

/**
 * Build user context for the offer generation call.
 * Used by both the offer agent (in the workflow) and the legacy single-call path.
 */
export function buildOfferContext(
  chosenRecommendation: {
    niche: string;
    bottleneck: string;
    your_solution: string;
    target_segment: { description: string; why: string };
    revenue_potential: {
      per_client: string;
      target_clients: number;
      monthly_total: string;
    };
    strategic_insight: string;
  },
  profile: {
    time_availability: string | null;
    revenue_goal: string | null;
  },
  answers: {
    location_city: string | null;
  }
): string {
  const lines: string[] = [];

  lines.push("## Chosen Niche");
  lines.push(`- Niche: ${chosenRecommendation.niche}`);
  lines.push(`- Target segment: ${chosenRecommendation.target_segment.description}`);
  lines.push(`- Why this segment: ${chosenRecommendation.target_segment.why}`);
  lines.push(`- Bottleneck: ${chosenRecommendation.bottleneck}`);
  lines.push(`- Solution: ${chosenRecommendation.your_solution}`);
  lines.push(`- Strategic insight: ${chosenRecommendation.strategic_insight}`);
  lines.push(`- Revenue potential: ${chosenRecommendation.revenue_potential.per_client} per client, ${chosenRecommendation.revenue_potential.target_clients} target clients, ${chosenRecommendation.revenue_potential.monthly_total}/month total`);

  lines.push("\n## User Context");
  lines.push(`- Revenue goal: ${profile.revenue_goal ?? "not specified"}`);
  lines.push(`- Time: ${profile.time_availability ?? "not specified"}`);
  lines.push(`- Delivery model: build_once`);
  lines.push(`- Location: ${answers.location_city ?? "not specified"}`);

  lines.push("\n## Cross-Agent Alignment");
  lines.push("A guarantee and pricing are being generated in parallel to form the complete offer. Your transformation copy must support both:");
  lines.push("- The guarantee will promise a specific, measurable outcome. Your 'transformation_to' must describe the state that the guarantee is promising. They must tell the same story.");
  lines.push("- The pricing will be value-based and premium. Your 'system_description' must describe the AI system's output in a way that justifies the price — describe what it PRODUCES, not what it IS.");

  return lines.join("\n");
}
