-- Add demo_config column to user_systems for AI-generated demo page configurations
ALTER TABLE public.user_systems ADD COLUMN IF NOT EXISTS demo_config jsonb;

COMMENT ON COLUMN public.user_systems.demo_config IS
  'AI-generated demo page configuration: agent_name, form_fields, scoring_prompt, hero copy, offer integration settings. Generated by demo-builder workflow.';
